modLoader="javafml"
loaderVersion="[47,)"
license="All Rights Reserved"

[[mods]]
modId="radioactive"
version="3.7.0"
displayName="Radioactive"
displayURL="https://www.curseforge.com/minecraft/mc-mods/radioactive-ll8"
logoFile="logo.png"
credits="Created using mod maker MCreator - https://mcreator.net/about"
authors="LightningLaser8"
description="Easy-to-use unified radiation system which allows all mods and datapacks in a modpack to use the same system of radiation."

# Start of user code block mod configuration
# End of user code block mod configuration

[[dependencies.radioactive]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1]"
    ordering="AFTER"
    side="BOTH"




# Start of user code block dependencies configuration
# End of user code block dependencies configuration